name: Docker Image CI # Actions名称

on: [push] # 执行时机

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: install
        run: yarn

      - name: build project
        run: yarn run build

      - name: Deploy to Server # 第四步，rsync推送文件
        uses: wlixcc/SFTP-Deploy-Action@v1.0  # 使用别人包装好的步骤镜像
        with:  
          username: 'root'   #ssh user name
          server: '${{ secrets.SSH_HOST }}' 
          ssh_private_key: '${{ secrets.DEPLOY_KEY }} '
          local_path: './dist/*'  # 对应我们项目build的文件夹路径
          remote_path: ' /www/wwwroot/myCloud/'